name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Node.js for frontend
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Check Node.js version
      run: node -v

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    - name: Run frontend tests
      working-directory: frontend
      run: npm test

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    # Setup Python for backend
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install backend dependencies
      working-directory: backend
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend tests
      working-directory: backend
      run: |
        source venv/bin/activate
        pytest tests

    - name: Build and run FastAPI
      working-directory: backend
      run: |
        source venv/bin/activate
        uvicorn main:app --host 0.0.0.0 --port 8080 &
        sleep 5  # give the server time to start
